### ISSUE TITLE
warnings reported by find bugs

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#10]
We ran FindBugs on the source and found the following list of errors:
Our build system doesn't accept source files with FindBugs issued warnings/errors.
Could these be fixed?

---

Manifest.java:82, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.app.Manifest.prefixes isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Presenter.java:189, ES_COMPARING_PARAMETER_STRING_WITH_EQ, Priority: High
    ES: Comparison of String parameter using == or != in com.skynav.ttpe.app.Presenter.getResourceState(String)
This code compares a java.lang.String parameter for reference equality using the == or != operators. Requiring callers to pass only String constants or interned strings to a method is unnecessarily fragile, and rarely leads to measurable performance gains. Consider using the equals(Object) method instead.

Presenter.java:580, RV_RETURN_VALUE_IGNORED_BAD_PRACTICE, Priority: Normal
    RV: Exceptional return value of java.io.File.mkdir() ignored in com.skynav.ttpe.app.Presenter.getFrameOutputStream(URI, File[])
This method returns a value that is not checked. The return value should be checked since it can indicate an unusual or unexpected function execution. For example, the File.delete() method returns false if the file could not be successfully deleted (rather than throwing an Exception). If you don't check the result, you won't notice if the method invocation signals unexpected behavior by returning an atypical return value.

FontCache.java:78, ES_COMPARING_PARAMETER_STRING_WITH_EQ, Priority: Normal
    ES: Comparison of String parameter using == or != in com.skynav.ttpe.fonts.FontCache.findExactMatch(List, FontStyle, FontWeight, String)
This code compares a java.lang.String parameter for reference equality using the == or != operators. Requiring callers to pass only String constants or interned strings to a method is unnecessarily fragile, and rarely leads to measurable performance gains. Consider using the equals(Object) method instead.

TransformMatrix.java:43, EI_EXPOSE_REP2, Priority: Normal
    EI2: new com.skynav.ttpe.geometry.TransformMatrix(double[]) may expose internal representation by storing an externally mutable object into TransformMatrix.m
This code stores a reference to an externally mutable object into the internal representation of the object.  If instances are accessed by untrusted code, and unchecked changes to the mutable object would compromise security or other important properties, you will need to do something different. Storing a copy of the object is better approach in many situations.

LayoutProcessor.java:92, REC_CATCH_EXCEPTION, Priority: Normal
    REC: Exception is caught when Exception is not thrown in com.skynav.ttpe.layout.LayoutProcessor.getProcessor(String, TransformerContext)
This method uses a try-catch block that catches Exception objects, but Exception is not thrown within the try block, and RuntimeException is not explicitly caught. It is a common bug pattern to say try { ... } catch (Exception e) { something } as a shorthand for catching a number of types of exception each of whose catch blocks is identical, but this construct also accidentally catches RuntimeException as well, masking potential bugs.
A better approach is to either explicitly catch the specific exceptions that are thrown, or to explicitly catch RuntimeException exception, rethrow it, and then catch all non-Runtime Exceptions, as shown below:
 try {
   ...
 } catch (RuntimeException e) {
   throw e;
 } catch (Exception e) {
   ... deal with all non-runtime exceptions ...
 }

LineLayout.java:369, DLS_DEAD_LOCAL_STORE, Priority: High
    DLS: Dead store to l in com.skynav.ttpe.layout.LineLayout.alignTextAreas(LineArea, double, InlineAlignment)
This instruction assigns a value to a local variable, but the value is not read or used in any subsequent instruction. Often, this indicates an error, because the value computed is never used.
Note that Sun's javac compiler often generates dead stores for final local variables. Because FindBugs is a bytecode-based tool, there is no easy way to eliminate these false positives.

LineLayout.java:406, URF_UNREAD_FIELD, Priority: Normal
    UrF: Unread field: com.skynav.ttpe.layout.LineLayout$WhitespaceState.whitespaceTreatment
This field is never read.  Consider removing it from the class.

AbstractFrameImage.java:57, EI_EXPOSE_REP, Priority: Normal
    EI: com.skynav.ttpe.render.AbstractFrameImage.getData() may expose internal representation by returning AbstractFrameImage.data
Returning a reference to a mutable object value stored in one of the object's fields exposes the internal representation of the object.  If instances are accessed by untrusted code, and unchecked changes to the mutable object would compromise security or other important properties, you will need to do something different. Returning a new copy of the object is better approach in many situations.

RenderProcessor.java:99, REC_CATCH_EXCEPTION, Priority: Normal
    REC: Exception is caught when Exception is not thrown in com.skynav.ttpe.render.RenderProcessor.getProcessor(String, TransformerContext)
This method uses a try-catch block that catches Exception objects, but Exception is not thrown within the try block, and RuntimeException is not explicitly caught. It is a common bug pattern to say try { ... } catch (Exception e) { something } as a shorthand for catching a number of types of exception each of whose catch blocks is identical, but this construct also accidentally catches RuntimeException as well, masking potential bugs.
A better approach is to either explicitly catch the specific exceptions that are thrown, or to explicitly catch RuntimeException exception, rethrow it, and then catch all non-Runtime Exceptions, as shown below:
 try {
   ...
 } catch (RuntimeException e) {
   throw e;
 } catch (Exception e) {
   ... deal with all non-runtime exceptions ...
 }

PNGRenderProcessor.java:242, NP_NULL_ON_SOME_PATH, Priority: Normal
    NP: Possible null pointer dereference of rectRegion in com.skynav.ttpe.render.png.PNGRenderProcessor.renderFrameImage(Document, Rectangle, Rectangle)
There is a branch of statement that, if executed, guarantees that a null value will be dereferenced, which would generate a NullPointerException when the code is executed. Of course, the problem might be that the branch or statement is infeasible and that the null pointer exception can't ever be executed; deciding that is beyond the ability of FindBugs.

SVGDocumentFrame.java:71, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.render.svg.SVGDocumentFrame.prefixes isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

XMLDocumentFrame.java:73, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.render.xml.XMLDocumentFrame.prefixes isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Color.java:156, VA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED, Priority: Normal
    FS: Format-string method String.format(String, Object[]) called with format string "#%02X%02X%02X" wants 3 arguments but is given 4 in com.skynav.ttpe.style.Color.toRGBAString(boolean)
A format-string method with a variable number of arguments is called, but more arguments are passed than are actually used by the format string. This won't cause a runtime exception, but the code may be silently omitting information that was intended to be included in the formatted string.

LineBreaker.java:137, DM_DEFAULT_ENCODING, Priority: High
    Dm: Found reliance on default encoding in com.skynav.ttpe.text.LineBreaker.main(String[]): new java.io.InputStreamReader(InputStream)
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

LineBreaker.java:147, DE_MIGHT_IGNORE, Priority: High
    DE: com.skynav.ttpe.text.LineBreaker.main(String[]) might ignore java.lang.Exception
This method might ignore an exception.  In general, exceptions should be handled or reported in some way, or they should be thrown out of the method.

Characters.java:34, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_HT isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:35, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_LF isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:36, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_VT isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:37, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_FF isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:38, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_CR isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:39, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_SPACE isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:40, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_NBSP isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:41, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_SPACE_EN_QUAD isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:52, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_SPACE_ZWSP isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:53, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_LINE_SEPARATOR isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:54, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_PARA_SEPARATOR isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:55, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_NNBSP isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:56, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_MMSP isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:58, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_OBJECT isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

Characters.java:59, MS_SHOULD_BE_FINAL, Priority: High
    MS: com.skynav.ttpe.util.Characters.UC_REPLACEMENT isn't final but should be
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

**Comment by shimada-development** [comment]
Addendum: Adding FindBugs plugin with eclipse IDE might be a good idea to catch any future warnings.

**Comment by skynavga** [comment]
Fixed in 20ab6cf1e442de6081b669d54949d48e917ed91b. Used .eclipse findbugs plug-in with all categories enabled, plus exclusion file findbugs.xml in top level ttpe directory.
