### ISSUE TITLE
option --external-extent not propagated to canvas area

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#11]
I used the following from the command line:
--external-extent 640px 480px

and got the following error from ttpe:
Usage: invalid option argument: external-extent: invalid syntax: 640px

Tried using the following way:
--external-extent "640px 480px"

This time, the processing went fine, but the generated output still was 720p

Am I using this option correctly?

**Comment by skynavga** [comment]
you are using properly, but the value from --external-extent isn't yet propagated to canvas area; upgrading this issue to bug

**Comment by skynavga** [comment]
Fixed in 8808750d016260ce72ff4e13df6574b83b2e519a.
