### ISSUE TITLE
request format change for origin and extent in manifest file

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#12]
Is it possible to generate the manifest having origin, extent (frame and image) specified in the following format? (i.e. replace "[A,B]" to "Apx Bpx")

frame b="10:01:28.033" e="10:01:29.1" x="1280px 720px"
image o="256px 610px" s="ttpi000002.png" x="768px 90px"
image o="1062px 144px" s="ttpi000003.png" x="90px 432px"

This will simplify ingesting this manifest to our format.

**Comment by skynavga** [comment]
Implemented in 841738aba66eb536672f4e5c2855ff76f4db88e8.
