### ISSUE TITLE
option to specify the output folder when not generating archive

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#14]
For a case when output is not archived, output is generated as a folder within output directory ("--output-directory").

Is it possible to generate the output images in output-directory? In the current approach, there is no good way to know what the output folder name is.

**Comment by skynavga** [comment]
Implemented in 51ef666d23413513fb4fe1d9019dca875f4ea9e9. Adds new `--output-directory-retained` option that takes the name of an existing directory into which retained frames, isd, and manifest are written. If used, then no more than one URL input can be specified.
