### ISSUE TITLE
platform dependency for rendering png images

### ISSUE THREAD

**Issue by shimada-development** [skynav/ttpe#18]
On different machines, "--output-format svg" seems to work fine (see attached image: renderedAsSvg.jpg: 
![renderedassvg](https://cloud.githubusercontent.com/assets/11282730/6836791/db82c854-d302-11e4-85bb-46119123eff3.jpg)
).

However, "--output-format png" seems to work differently (see attached image renderedAsPng.jpg: 
![renderedaspng](https://cloud.githubusercontent.com/assets/11282730/6836812/feffe898-d302-11e4-98f2-f60dffd79e13.jpg)

What are the platform dependencies (possibly system fonts etc. or a lib package availability) prerequisites to get ttpe render png images properly.

**Comment by skynavga** [comment]
depending on the system, it may be necessary to ensure that the open type (*.otf) fonts found in the tst/fonts directory of the TTPE source distribution be installed as system fonts; if that doesn't work, then additional investigation will be necessary;

note that when you run TTPE to generate SVG files, TTPE is directly accessing the font files in ttpe.jar (by means of the fontbox packages); however, when TTPE is generating PNG files, it uses the batik package, which uses its own font access mechanisms and configuration;

if batik isn't finding a known installed font file, then some additional investigation will be required to determine why it isn't finding it

**Comment by shimada-development** [comment]
Even in SGV rendering, I believe an explicit option of "--font-directory <font-dir>" is needed. Isn't that right?

**Comment by skynavga** [comment]
correct, TTPE will read the font(s) (via fontbox) no matter the renderer, since it needs font metrics to perform layout; however, only the PNG renderer (via batik) uses the font glyphs during rasterization

**Comment by skynavga** [comment]
After switching from Oracle JDK to OpenJDK

<pre>
ubuntu@ip-172-31-25-141:~/skynav$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
ubuntu@ip-172-31-25-141:~/
</pre>

and installing `NotoSansJP` fonts into `/usr/share/fonts/truetype/noto`

<pre>
ubuntu@ip-172-31-25-141:~/skynav$ fc-list "Noto Sans JP"
/usr/share/fonts/truetype/noto/NotoSansJP-Bold.otf: Noto Sans JP,Noto Sans JP Bold:style=Bold,Regular
/usr/share/fonts/truetype/noto/NotoSansJP-Regular.otf: Noto Sans JP,Noto Sans JP Regular:style=Regular
</pre>

we find that running TTPE succeeds as expected (producing):

![ttpi000001](https://cloud.githubusercontent.com/assets/377455/7000269/33c7d80c-dbdb-11e4-9f0a-5da3b81ec118.png)
