### ISSUE TITLE
digits in vertical text overlap following text

### ISSUE THREAD

**Issue by shinjantiwary** [skynav/ttpe#8]
begin="10:02:38:05" end="10:02:40:14" region="縦右" style="s1">10月12日
Seems like "12" is overlapping with "日" in the final .png output
![ttpi000015](https://cloud.githubusercontent.com/assets/11201995/6495407/aadc8c2e-c27e-11e4-9645-71fde6737b48.png)

**Comment by skynavga** [comment]
This issue was moved to skynav/ttt#21
